#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Translate all Chinese content in the project to English.
Handles: main/*.md files, custom.css, Keyword Stats CSV
"""

import os
import re
import shutil

BASE = r'D:\Makeup-related'

# ============================================================
# Translation maps for each file
# ============================================================

TRANSLATIONS = {
    # ---- Common terms ----
    '项目概述': 'Project Overview',
    '核心特性': 'Core Features',
    '资源包结构': 'Resource Package Structure',
    '快速开始': 'Quick Start',
    '安装依赖': 'Install Dependencies',
    '本地开发': 'Local Development',
    '构建生产版本': 'Build Production Version',
    '预览构建结果': 'Preview Build Result',
    '核心文档索引': 'Core Documentation Index',
    '文档': 'Document',
    '路径': 'Path',
    '说明': 'Description',
    '关键设计决策': 'Key Design Decisions',
    '为什么选择': 'Why Choose',
    '为什么采用': 'Why Adopt',
    '核心功能亮点': 'Core Feature Highlights',
    '滚动公告栏': 'Scrolling Marquee Banner',
    '顶部固定滚动条': 'Fixed top scrolling bar',
    '展示全球用户下单信息': 'Displays global user order information',
    '增强信任感和社会证明': 'Enhances trust and social proof',
    '文章页操作按钮注入': 'Article Page Action Button Injection',
    '在每篇文章标题下方自动注入两个': 'Automatically injects two',
    '主按钮': 'Primary Button',
    '次按钮': 'Secondary Button',
    '结构化数据': 'Structured Data',
    '为每篇文章自动生成': 'Automatically generates for each article',
    '文章元数据': 'Article metadata',
    '常见问题': 'FAQ',
    '站点信息': 'Site information',
    '三栏文档布局': 'Three-Column Document Layout',
    '左栏': 'Left Column',
    '中栏': 'Middle Column',
    '右栏': 'Right Column',
    '品牌目录': 'Brand Directory',
    '热门交易推荐': 'Trending Deals',
    'SEO 优化': 'SEO Optimization',
    '自动生成': 'Auto-generate',
    '每页独立的': 'Per-page independent',
    '集成': 'Integration',
    '配置': 'Configuration',
    '语义化': 'Semantic',
    '内容组织策略': 'Content Organization Strategy',
    '文章类型': 'Article Types',
    '平台评测': 'Platform Review',
    '产品评测': 'Product Review',
    '季节穿搭': 'Seasonal Style',
    '工具': 'Tool',
    '平台对比': 'Platform Comparison',
    '规范': 'Specification',
    '是否生成': 'Whether to generate',
    '转化率优化': 'Conversion Rate Optimization',
    '布局': 'Layout',
    '首页': 'Homepage',
    '文章页标题下': 'Below article title',
    '双按钮': 'Dual buttons',
    '左侧栏': 'Left sidebar',
    '品牌目录链接到': 'Brand directory links to',
    '右侧栏': 'Right sidebar',
    '热门交易链接到': 'Trending deals links to',
    '底部浮动按钮': 'Bottom floating button',
    '社区邀请': 'Community invitation',
    '社会证明': 'Social Proof',
    '滚动公告栏展示全球用户活动': 'Scrolling marquee shows global user activity',
    '统计数据展示': 'Statistics display',
    '国家': 'Countries',
    '用户': 'Users',
    '订单': 'Orders',
    '品牌': 'Brand',
    '展示': 'Display',
    '性能优化': 'Performance Optimization',
    '图片优化': 'Image Optimization',
    '使用': 'Use',
    '格式': 'Format',
    '体积小': 'Smaller size',
    '响应式图片': 'Responsive images',
    '懒加载': 'Lazy loading',
    '内置': 'Built-in',
    '图片压缩': 'Image compression',
    '代码优化': 'Code Optimization',
    '变量复用': 'Variable reuse',
    '组件按需加载': 'On-demand component loading',
    '路由级代码分割': 'Route-level code splitting',
    '最小化': 'Minimize',
    '缓存策略': 'Caching Strategy',
    '自动缓存静态资源': 'Auto-cache static assets',
    '浏览器缓存控制': 'Browser cache control',
    '边缘缓存': 'Edge caching',
    '扩展指南': 'Extension Guide',
    '添加新文章': 'Add New Article',
    '在': 'In',
    '下创建新文件夹': 'create a new folder',
    '创建': 'Create',
    '文件': 'File',
    '包含': 'Include',
    '添加封面图片到': 'Add cover image to',
    '在': 'In',
    '中添加分类条目': 'add category entry',
    '添加新平台': 'Add New Platform',
    '在': 'In',
    '下添加平台': 'add platform',
    '格式': 'Format',
    '编辑': 'Edit',
    '添加平台卡片': 'Add platform card',
    '修改品牌目录': 'Modify Brand Directory',
    '编辑': 'Edit',
    '中的': 'in',
    '数组': 'array',
    '添加': 'Add',
    '在文章': 'In article',
    '中添加': 'add',
    '在': 'In',
    '的': "'s",
    '对象中添加': 'object add',
    '数据': 'Data',
    '监控与分析': 'Monitoring & Analytics',
    '追踪': 'Tracking',
    '页面浏览事件': 'Page view events',
    '用户行为分析': 'User behavior analysis',
    '转化漏斗追踪': 'Conversion funnel tracking',
    '提交': 'Submit',
    '监控索引状态': 'Monitor index status',
    '查看搜索表现': 'View search performance',
    '修复爬取错误': 'Fix crawl errors',
    '流量统计': 'Traffic statistics',
    '性能指标': 'Performance metrics',
    '安全防护': 'Security protection',
    '缓存命中率': 'Cache hit rate',
    '最佳实践': 'Best Practices',
    '每篇文章包含唯一的': 'Each article includes unique',
    '使用语义化': 'Use semantic',
    '所有图片包含描述性': 'All images include descriptive',
    '内部链接使用相对路径': 'Internal links use relative paths',
    '外部链接添加': 'External links add',
    '内容创作最佳实践': 'Content Creation Best Practices',
    '标题包含目标关键词': 'Title includes target keywords',
    '描述控制在': 'Description控制在',
    '字符': 'characters',
    '使用': 'Use',
    '组织内容结构': 'to organize content structure',
    '每篇文章至少': 'Each article at least',
    '字': 'words',
    '包含内部和外部链接': 'Include internal and external links',
    '性能最佳实践': 'Performance Best Practices',
    '图片使用': 'Images use',
    '压缩所有静态资源': 'Compress all static assets',
    '使用': 'Use',
    '分发内容': 'to distribute content',
    '最小化第三方脚本': 'Minimize third-party scripts',
    '启用浏览器缓存': 'Enable browser caching',
    '如何修改网站的主色调': 'How to change the website primary color',
    '编辑': 'Edit',
    '中的': 'in',
    '变量': 'variables',
    '主色': 'Primary color',
    '渐变辅助色': 'Gradient accent color',
    '如何添加新的导航菜单项': 'How to add new navigation menu items',
    '编辑': 'Edit',
    '中的': 'in',
    '数组': 'array',
    '如何禁用某篇文章的索引': 'How to disable indexing for an article',
    '在文章的': "In the article's",
    '中添加': 'add',
    '如何更新': 'How to update',
    '追踪': 'tracking',
    '编辑': 'Edit',
    '中的': 'in',
    '技术栈总结': 'Tech Stack Summary',
    '技术': 'Technology',
    '版本': 'Version',
    '用途': 'Purpose',
    '静态站点生成器': 'Static Site Generator',
    '组件框架': 'Component Framework',
    '内容格式': 'Content Format',
    '部署平台': 'Deployment Platform',
    '流量分析': 'Traffic Analytics',
    '数据管理': 'Data Management',
    '社区建设': 'Community Building',
    '联系与支持': 'Contact & Support',
    '社区': 'Community',
    '项目仓库': 'Project Repository',
    '在线站点': 'Live Site',
    '文档版本': 'Document Version',
    '最后更新': 'Last Updated',
    '维护者': 'Maintainer',

    # ---- 01-技术选型说明 ----
    '技术选型说明': 'Technology Selection Guide',
    '概述': 'Overview',
    '本文档详细说明了': 'This document details',
    '项目的技术栈选择及其理由': "project's technology stack choices and rationale",
    '每个技术选择都基于项目需求': 'Each technology choice is based on project requirements',
    '性能要求': 'performance requirements',
    '开发效率': 'development efficiency',
    '和运维成本等因素综合考虑': 'and operational cost considerations',
    '核心技术栈': 'Core Technology Stack',
    '选择理由': 'Selection Rationale',
    '极快的构建速度': 'Extremely Fast Build Speed',
    '基于': 'Based on',
    '构建工具': 'build tool',
    '开发环境热更新即时生效': 'Development environment hot reload takes effect instantly',
    '生产构建速度比传统': 'Production build speed is',
    '快': 'faster than traditional',
    '倍': 'times',
    '适合频繁更新的内容型网站': 'Suitable for frequently updated content websites',
    '友好': 'Friendly',
    '静态': 'Static',
    '输出': 'output',
    '搜索引擎可直接抓取': 'Search engines can directly crawl',
    '支持自定义': 'Supports custom',
    '标签': 'tags',
    '支持': 'Supports',
    '无': 'No',
    '后缀': 'suffix',
    '集成': 'Integration',
    '可以': 'Can',
    '组件扩展功能': 'use components to extend functionality',
    '支持': 'Supports',
    '主题定制灵活': 'Flexible theme customization',
    '可完全自定义布局': 'Fully customizable layout',
    '组件复用性强': 'Strong component reusability',
    '优先': 'First',
    '内容创作简单直观': 'Content creation is simple and intuitive',
    '非技术人员也能上手': 'Non-technical users can get started',
    '支持': 'Supports',
    '元数据': 'metadata',
    '支持自定义容器': 'Supports custom containers',
    '代码高亮': 'code highlighting',
    '表格等': 'tables, etc.',
    '可嵌入': 'Can embed',
    '组件': 'components',
    '系统': 'System',
    '默认主题功能完善': 'Default theme is fully featured',
    '支持完全自定义主题': 'Supports fully custom themes',
    '布局插槽灵活': 'Flexible layout slots',
    '等': 'etc.',
    '可覆盖默认组件': 'Can override default components',
    '替代方案对比': 'Alternative Comparison',
    '方案': 'Solution',
    '优点': 'Pros',
    '缺点': 'Cons',
    '结论': 'Conclusion',
    '生态丰富': 'Rich ecosystem',
    '插件多': 'Many plugins',
    '性能差': 'Poor performance',
    '安全隐患': 'Security risks',
    '维护成本高': 'High maintenance cost',
    '不适合静态内容站': 'Not suitable for static content sites',
    '功能强大': 'Powerful features',
    '支持': 'Supports',
    '学习曲线陡': 'Steep learning curve',
    '构建慢': 'Slow build',
    '过度设计': 'Over-engineered',
    '构建速度快': 'Fast build speed',
    '模板语法复杂': 'Complex template syntax',
    '扩展性差': 'Poor extensibility',
    '不适合复杂交互': 'Not suitable for complex interactions',
    '原生支持': 'Native support',
    '构建速度慢': 'Slow build speed',
    '插件依赖': 'Plugin dependency',
    '性能不足': 'Insufficient performance',
    '速度快': 'Fast speed',
    '好': 'Good',
    '生态相对年轻': 'Relatively young ecosystem',
    '最佳选择': 'Best Choice',
    '渐进式框架': 'Progressive Framework',
    '可以按需引入': 'Can import on demand',
    '体积小': 'Small size',
    '学习曲线平缓': 'Gentle learning curve',
    '与': 'With',
    '深度集成': 'deep integration',
    '逻辑复用性强': 'Strong logic reusability',
    '代码组织更清晰': 'Clearer code organization',
    '支持好': 'Good support',
    '响应式系统': 'Reactive System',
    '自动追踪依赖': 'Automatic dependency tracking',
    '性能优化自动': 'Automatic performance optimization',
    '开发体验好': 'Good development experience',
    '组件化开发': 'Component-Based Development',
    '组件复用性高': 'High component reusability',
    '维护成本低': 'Low maintenance cost',
    '团队协作友好': 'Team collaboration friendly',
    '在': 'In',
    '中的': "'s",
    '应用': 'Application',
    '自定义主题组件': 'Custom theme components',
    '布局组件': 'Layout components',
    '交互组件': 'Interactive components',
    '样式定制': 'Style customization',
    '全球': 'Global',
    '自动分发到全球': 'Auto-distribute to global',
    '边缘节点': 'edge nodes',
    '访问速度快': 'Fast access speed',
    '延迟低': 'Low latency',
    '适合全球用户访问': 'Suitable for global user access',
    '免费额度充足': 'Sufficient free quota',
    '每月': 'Monthly',
    '次构建': 'builds',
    '无限带宽': 'Unlimited bandwidth',
    '支持自定义域名': 'Supports custom domains',
    '免费': 'Free',
    '证书': 'certificate',
    '自动部署': 'Auto Deployment',
    '推送自动触发构建': 'Push auto-triggers build',
    '支持分支部署': 'Supports branch deployment',
    '预览环境': 'Preview environment',
    '部署速度快': 'Fast deployment speed',
    '通常': 'Usually',
    '分钟': 'minutes',
    '优异': 'Excellent',
    '评分接近满分': 'Score close to perfect',
    '自动优化图片': 'Auto-optimize images',
    '支持': 'Supports',
    '和': 'and',
    '防护': 'Protection',
    '应用防火墙': 'Application Firewall',
    '管理': 'Management',
    '部署简单': 'Simple deployment',
    '预览环境好': 'Good preview environment',
    '国内访问慢': 'Slow domestic access',
    '免费额度有限': 'Limited free quota',
    '不适合全球市场': 'Not suitable for global market',
    '功能丰富': 'Rich features',
    '表单处理': 'Form processing',
    '构建时间长': 'Long build time',
    '免费': 'Free',
    '简单': 'Simple',
    '构建慢': 'Slow build',
    '功能有限': 'Limited features',
    '功能不足': 'Insufficient features',
    '灵活': 'Flexible',
    '可扩展': 'Scalable',
    '配置复杂': 'Complex configuration',
    '成本高': 'High cost',
    '过度设计': 'Over-engineered',
    '全球': 'Global',
    '免费额度大': 'Large free quota',
    '速度快': 'Fast speed',
    '功能相对简单': 'Relatively simple features',
    '创作简单': 'Simple creation',
    '语法直观': 'Intuitive syntax',
    '学习成本低': 'Low learning cost',
    '非技术人员也能上手': 'Non-technical users can get started',
    '支持富文本编辑器': 'Supports rich text editors',
    '版本控制友好': 'Version Control Friendly',
    '纯文本格式': 'Plain text format',
    '差异对比清晰': 'Clear diff comparison',
    '易于协作': 'Easy collaboration',
    '可转换性强': 'Strong Convertibility',
    '可转换为': 'Can convert to',
    '等': 'etc.',
    '支持自定义扩展': 'Supports custom extensions',
    '可嵌入代码块': 'Can embed code blocks',
    '表格': 'tables',
    '图片等': 'images, etc.',
    '易于提取元数据': 'Easy to extract metadata',
    '扩展': 'Extension',
    '辅助工具和服务': 'Auxiliary Tools and Services',
    '免费的流量分析工具': 'Free traffic analytics tool',
    '功能强大': 'Powerful features',
    '支持自定义事件': 'Supports custom events',
    '与': 'With',
    '集成': 'integration',
    '支持转化追踪': 'Supports conversion tracking',
    '在': 'In',
    '的': "'s",
    '中注入': 'inject in',
    '脚本': 'script',
    '免费': 'Free',
    '易用的数据管理工具': 'easy-to-use data management tool',
    '支持实时协作': 'Supports real-time collaboration',
    '可嵌入到网站中': 'Can embed in website',
    '作为核心产品推广': 'Promoted as core product',
    '通过外部链接集成': 'Integrated via external links',
    '所有': 'All',
    '按钮指向': 'buttons point to',
    '免费的社区建设工具': 'Free community building tool',
    '支持文字': 'Supports text',
    '语音': 'voice',
    '视频交流': 'video communication',
    '用户活跃度高': 'High user activity',
    '适合建立忠实用户群体': 'Suitable for building loyal user base',
    '底部浮动按钮': 'Bottom floating button',
    '链接到': 'Links to',
    '社区': 'community',
    '图片格式': 'Image Format',
    '体积比': 'Size is',
    '小': 'smaller than',
    '质量更好': 'Better quality',
    '支持透明通道': 'Supports transparency',
    '现代浏览器广泛支持': 'Widely supported by modern browsers',
    '兼容性处理': 'Compatibility Handling',
    '自动处理图片优化': 'Auto-handles image optimization',
    '无需额外配置': 'No extra configuration needed',
    '层次': 'Layer',
    '组件化开发': 'Component Development',
    '总结': 'Summary',
    '选型原则': 'Selection Principles',
    '性能优先': 'Performance First',
    '选择构建速度快': 'Choose fast build speed',
    '加载速度快的技术': 'and fast loading technologies',
    '优先选择静态输出': 'Prioritize static output',
    '支持自定义': 'supports custom',
    '的技术': 'technologies',
    '选择学习曲线平缓': 'Choose gentle learning curve',
    '文档完善的技术': 'well-documented technologies',
    '优先选择免费额度充足': 'Prioritize sufficient free quota',
    '自动化程度高的技术': 'high automation technologies',
    '可扩展性': 'Extensibility',
    '选择易于扩展': 'Choose easily extensible',
    '支持自定义的技术': 'supports custom technologies',
    '用户体验': 'User Experience',
    '选择访问速度快': 'Choose fast access speed',
    '交互流畅的技术': 'smooth interaction technologies',
    '未来技术演进': 'Future Technology Evolution',
    '可能的技术升级': 'Possible Technology Upgrades',
    '增强代码类型安全': 'Enhance code type safety',
    '支持离线访问': 'Support offline access',
    '使用': 'Use',
    '或': 'or',
    '管理内容': 'to manage content',
    '搜索功能': 'Search Function',
    '集成': 'Integrate',
    '评论系统': 'Comment System',
    '集成': 'Integrate',
    '或': 'or',
    '技术债务': 'Technical Debt',
    '硬编码数据': 'Hardcoded Data',
    '部分数据': 'Some data',
    '如品牌目录': 'such as brand directory',
    '热门交易': 'trending deals',
    '硬编码在组件中': 'hardcoded in components',
    '应迁移到配置文件': 'should migrate to config files',
    '样式重复': 'Style Duplication',
    '部分样式在多个组件中重复': 'Some styles are duplicated across components',
    '应提取到全局样式': 'should extract to global styles',
    '测试覆盖': 'Test Coverage',
    '缺少自动化测试': 'Lacks automated testing',
    '应添加单元测试和端到端测试': 'should add unit and end-to-end tests',
    '本项目的技术选型遵循': "This project's technology selection follows",
    '的原则': 'principles',
    '选择了一个成熟': 'choosing a mature',
    '稳定': 'stable',
    '高效的技术栈': 'efficient tech stack',
    '的组合': 'combination',
    '既满足了性能和': 'satisfies both performance and',
    '要求': 'requirements',
    '又保证了开发效率和运维便利性': 'while ensuring development efficiency and operational convenience',
    '这套技术栈特别适合内容型网站': 'This tech stack is especially suitable for content websites',
    '博客': 'blogs',
    '文档站点和': 'documentation sites and',
    '营销站点': 'marketing sites',
    '如果你的项目需求类似': 'If your project needs are similar',
    '可以参考这套技术选型方案': 'you can reference this technology selection plan',

    # ---- 02-项目架构 ----
    '项目架构文档': 'Project Architecture Document',
    '本文档详细说明了': 'This document details',
    '项目的整体架构设计': "project's overall architecture design",
    '包括目录结构': 'including directory structure',
    '组件关系': 'component relationships',
    '数据流和模块划分': 'data flow and module division',
    '理解项目架构有助于快速上手开发和维护': 'Understanding the project architecture helps quickly get started with development and maintenance',
    '整体架构图': 'Overall Architecture Diagram',
    '全球': 'Global',
    '分发': 'Distribution',
    '静态站点': 'Static Site',
    '自定义主题层': 'Custom Theme Layer',
    '品牌目录': 'Brand Directory',
    '热门交易': 'Trending Deals',
    '滚动公告': 'Scrolling Marquee',
    '文章索引': 'Article Index',
    '样式系统': 'Style System',
    '核心': 'Core',
    '解析器': 'Parser',
    '组件系统': 'Component System',
    '构建工具': 'Build Tool',
    '目录结构': 'Directory Structure',
    '配置和主题': 'Configuration and Theme',
    '核心配置文件': 'Core configuration file',
    '自定义主题': 'Custom theme',
    '主题入口': 'Theme entry point',
    '全局样式': 'Global styles',
    '三栏布局组件': 'Three-column layout component',
    '左侧品牌目录': 'Left brand directory',
    '右侧热门交易': 'Right trending deals',
    '顶部滚动公告': 'Top scrolling marquee',
    '文章索引页': 'Article index page',
    '文章内容': 'Article content',
    '文章索引页': 'Article index page',
    '平台评测': 'Platform review',
    '产品评测': 'Product review',
    '季节穿搭': 'Seasonal style',
    '静态资源': 'Static assets',
    '网站图标': 'Website icon',
    '爬虫规则': 'Crawler rules',
    '图片资源': 'Image resources',
    '产品封面图': 'Product cover images',
    '平台': 'Platform',
    '核心组件关系': 'Core Component Relationships',
    '主题入口': 'Theme Entry',
    '职责': 'Responsibilities',
    '扩展默认主题': 'Extend default theme',
    '注册全局组件': 'Register global components',
    '注入全局样式': 'Inject global styles',
    '处理路由事件': 'Handle routing events',
    '动态注入': 'Dynamically inject',
    '元素': 'elements',
    '关键功能': 'Key Functions',
    '拦截': 'Intercept',
    '链接': 'links',
    '处理': 'Handle',
    '导航': 'navigation',
    '注入滚动公告栏': 'Inject scrolling marquee',
    '注入': 'Inject',
    '浮动按钮': 'floating button',
    '动态注入文章操作按钮': 'Dynamically inject article action buttons',
    '三栏布局': 'Three-Column Layout',
    '提供三栏网格布局': 'Provide three-column grid layout',
    '集成左侧栏和右侧栏': 'Integrate left and right sidebars',
    '响应式适配': 'Responsive adaptation',
    '布局结构': 'Layout Structure',
    '标题栏': 'Title Bar',
    '主内容区': 'Main Content Area',
    '响应式断点': 'Responsive Breakpoints',
    '三栏布局': 'Three-column layout',
    '单栏布局': 'Single-column layout',
    '侧边栏移到主内容下方': 'Sidebar moves below main content',
    '左侧品牌目录': 'Left Brand Directory',
    '展示品牌分类目录': 'Display brand category directory',
    '提供快速导航': 'Provide quick navigation',
    '链接到': 'Link to',
    '数据结构': 'Data Structure',
    '特点': 'Features',
    '粘性定位': 'Sticky positioning',
    '可滚动': 'Scrollable',
    '自定义滚动条样式': 'Custom scrollbar style',
    '右侧热门交易': 'Right Trending Deals',
    '展示热门产品推荐': 'Display trending product recommendations',
    '提供': 'Provide',
    '链接': 'links',
    '增强转化率': 'Enhance conversion rate',
    '徽章标记': 'Badge markers',
    '悬停动画效果': 'Hover animation effects',
    '顶部滚动公告': 'Top Scrolling Marquee',
    '展示全球用户活动': 'Display global user activity',
    '增强社会证明': 'Enhance social proof',
    '提升信任感': 'Boost trust',
    '实现方式': 'Implementation',
    '动画': 'Animation',
    '无限水平滚动': 'Infinite horizontal scrolling',
    '鼠标悬停暂停': 'Pause on hover',
    '启用': 'Enable',
    '加速': 'acceleration',
    '流畅动画': 'Smooth animation',
    '文章索引页': 'Article Index Page',
    '展示所有文章分类': 'Display all article categories',
    '提供筛选导航': 'Provide filter navigation',
    '两栏布局': 'Two-column layout',
    '主内容': 'Main content',
    '侧边栏': 'Sidebar',
    '分类维度': 'Category Dimensions',
    '季节选择': 'Season Selection',
    '批次精选': 'Batch Picks',
    '产品评测': 'Product Review',
    '可扩展的分类系统': 'Extensible category system',
    '彩色标签设计': 'Colorful tag design',
    '响应式网格布局': 'Responsive grid layout',
    '数据流': 'Data Flow',
    '内容数据流': 'Content Data Flow',
    '文件': 'Files',
    '解析': 'Parse',
    '生成页面元数据': 'Generate page metadata',
    '处理': 'Processing',
    '注入': 'Inject',
    '渲染为': 'Render as',
    '主题数据流': 'Theme Data Flow',
    '接收配置': 'Receive configuration',
    '自定义': 'Custom',
    '组件': 'Component',
    '插槽注入': 'Slot injection',
    '渲染全局组件': 'Render global components',
    '用户交互数据流': 'User Interaction Data Flow',
    '用户点击': 'User clicks',
    '按钮': 'button',
    '事件处理器': 'Event handler',
    '打开新标签': 'Open new tab',
    '跳转到': 'Navigate to',
    '追踪事件': 'Track event',
    '可选': 'Optional',
    '模块划分': 'Module Division',
    '配置模块': 'Configuration Module',
    '站点基本信息': 'Site basic information',
    '导航配置': 'Navigation configuration',
    '构建配置': 'Build configuration',
    '页面数据转换': 'Page data transformation',
    '主题模块': 'Theme Module',
    '定义样式系统': 'Define style system',
    '处理全局事件': 'Handle global events',
    '组件模块': 'Component Module',
    '实现': 'Implement',
    '处理组件逻辑': 'Handle component logic',
    '管理组件状态': 'Manage component state',
    '内容模块': 'Content Module',
    '提供页面内容': 'Provide page content',
    '定义': 'Define',
    '组织内容结构': 'Organize content structure',
    '内部链接': 'Internal links',
    '资源模块': 'Resource Module',
    '提供静态资源': 'Provide static assets',
    '图片优化': 'Image optimization',
    '图标管理': 'Icon management',
    '关键设计模式': 'Key Design Patterns',
    '组件组合模式': 'Component Composition Pattern',
    '组织组件逻辑': 'Organize component logic',
    '插槽注入模式': 'Slot Injection Pattern',
    '利用': 'Utilize',
    '的布局插槽注入全局组件': "'s layout slots to inject global components",
    '响应式设计模式': 'Responsive Design Pattern',
    '使用': 'Use',
    '和媒体查询实现响应式布局': 'and media queries to implement responsive layout',
    '数据驱动模式': 'Data-Driven Pattern',
    '通过数据数组驱动组件渲染': 'Drive component rendering through data arrays',
    '代码分割': 'Code Splitting',
    '自动进行路由级代码分割': 'Automatically performs route-level code splitting',
    '每个页面只加载必要的资源': 'Each page only loads necessary resources',
    '使用': 'Use',
    '格式': 'Format',
    '响应式图片': 'Responsive images',
    '懒加载': 'Lazy loading',
    '内置': 'Built-in',
    '优化': 'Optimization',
    '复用': 'Reuse',
    '最小化重绘重排': 'Minimize repaint and reflow',
    '使用': 'Use',
    '代替': 'instead of',
    '事件委托': 'Event delegation',
    '防抖节流': 'Debounce and throttle',
    '异步加载第三方脚本': 'Async load third-party scripts',
    '扩展点': 'Extension Points',
    '添加新组件': 'Add New Component',
    '在': 'In',
    '目录下创建新的': 'directory create new',
    '文件': 'file',
    '然后在': 'then in',
    '中注册': 'register',
    '添加新页面': 'Add New Page',
    '在根目录或子目录下创建': 'Create in root or subdirectory',
    '文件': 'file',
    '自动生成路由': 'auto-generate route',
    '添加新布局': 'Add New Layout',
    '在': 'In',
    '目录下创建新的布局组件': 'directory create new layout component',
    '然后在': 'then in',
    '中指定': 'specify',
    '添加新样式': 'Add New Styles',
    '在': 'In',
    '中添加全局样式': 'add global styles',
    '或在组件中使用': 'or use in components',
    '架构优势': 'Architecture Advantages',
    '清晰的分层': 'Clear layering',
    '配置层': 'Configuration layer',
    '主题层': 'Theme layer',
    '组件层': 'Component layer',
    '内容层': 'Content layer',
    '资源层分离': 'Resource layer separation',
    '高内聚低耦合': 'High cohesion low coupling',
    '每个组件职责单一': 'Each component has single responsibility',
    '依赖关系清晰': 'Clear dependency relationships',
    '易于扩展': 'Easy to extend',
    '模块化设计': 'Modular design',
    '新增功能不影响现有代码': 'New features do not affect existing code',
    '性能优异': 'Excellent performance',
    '静态输出': 'Static output',
    '代码分割': 'Code splitting',
    '图片优化': 'Image optimization',
    '语义化': 'Semantic',
    '友好': 'friendly',
    '结构化数据': 'Structured data',
    '架构挑战': 'Architecture Challenges',
    '硬编码数据': 'Hardcoded Data',
    '部分数据硬编码在组件中': 'Some data is hardcoded in components',
    '修改需要重新构建': 'Modifications require rebuild',
    '状态管理': 'State Management',
    '缺少全局状态管理': 'Lacks global state management',
    '组件间通信依赖': 'Inter-component communication depends on',
    '测试覆盖': 'Test Coverage',
    '缺少自动化测试': 'Lacks automated testing',
    '重构风险较高': 'Higher refactoring risk',
    '未来演进方向': 'Future Evolution Direction',
    '引入': 'Introduce',
    '将内容管理从': 'Migrate content management from',
    '迁移到': 'to',
    '添加搜索功能': 'Add search functionality',
    '集成': 'Integrate',
    '引入状态管理': 'Introduce state management',
    '使用': 'Use',
    '管理全局状态': 'to manage global state',
    '添加自动化测试': 'Add automated testing',
    '使用': 'Use',
    '和': 'and',
    '支持': 'Support',
    '添加': 'Add',
    '支持离线访问': 'Support offline access',
    '本项目采用了一个清晰': 'This project adopts a clear',
    '简洁': 'concise',
    '高效的架构设计': 'efficient architecture design',
    '作为核心框架': 'As the core framework',
    '提供了强大的静态站点生成能力': 'provides powerful static site generation capabilities',
    '作为组件系统': 'As the component system',
    '提供了灵活的': 'provides flexible',
    '开发体验': 'development experience',
    '作为部署平台': 'As the deployment platform',
    '提供了全球': 'provides global',
    '分发能力': 'distribution capabilities',
    '这套架构特别适合内容型网站': 'This architecture is especially suitable for content websites',
    '博客': 'blogs',
    '文档站点和': 'documentation sites and',
    '营销站点': 'marketing sites',
    '如果你的项目需求类似': 'If your project needs are similar',
    '可以参考这套架构设计': 'you can reference this architecture design',

    # ---- 04-设计规范 ----
    '设计规范文档': 'Design Specification Document',
    '本文档定义了': 'This document defines',
    '的': "'s",
    '设计规范': 'design specification',
    '包括颜色系统': 'including color system',
    '排版体系': 'typography system',
    '组件样式': 'component styles',
    '响应式策略和交互模式': 'responsive strategy and interaction patterns',
    '所有自定义样式集中在': 'All custom styles are centralized in',
    '颜色系统': 'Color System',
    '品牌色': 'Brand Colors',
    '主品牌色': 'Primary brand color',
    '蓝紫渐变起点': 'Blue-purple gradient start',
    '辅助品牌色': 'Secondary brand color',
    '蓝紫渐变终点': 'Blue-purple gradient end',
    '渐变方案': 'Gradient Scheme',
    '用途': 'Usage',
    '渐变值': 'Gradient Value',
    '示例': 'Example',
    '主渐变': 'Primary gradient',
    '按钮': 'Button',
    '标题背景': 'Title background',
    '区域': 'Area',
    '统计数字': 'Statistics number',
    '背景渐变': 'Background gradient',
    '卡片悬停': 'Card hover',
    '相关文章区域': 'Related articles area',
    '滚动条渐变': 'Scrollbar gradient',
    '顶部': 'Top',
    '微透明背景': 'Semi-transparent background',
    '侧边栏链接': 'Sidebar links',
    '语义色': 'Semantic Colors',
    '语义': 'Semantic',
    '色值': 'Color Value',
    '热门': 'Hot',
    '紧急': 'Urgent',
    '徽章': 'Badge',
    '趋势': 'Trending',
    '警告': 'Warning',
    '补货': 'Restock',
    '成功': 'Success',
    '悬停': 'Hover',
    '中性色': 'Neutral Colors',
    '亮色模式': 'Light Mode',
    '页面背景': 'Page background',
    '主文本': 'Primary text',
    '次要文本': 'Secondary text',
    '暗色模式': 'Dark Mode',
    '组件特定颜色': 'Component-Specific Colors',
    '组件': 'Component',
    '亮色背景': 'Light Background',
    '暗色背景': 'Dark Background',
    '边框色': 'Border Color',
    '统计卡片': 'Stat Card',
    '文章卡片': 'Article Card',
    '侧边栏': 'Sidebar',
    '指南卡片': 'Guide Card',
    '平台卡片': 'Platform Card',
    '排版体系': 'Typography System',
    '字体': 'Font',
    '字号层级': 'Font Size Hierarchy',
    '元素': 'Element',
    '桌面端': 'Desktop',
    '移动端': 'Mobile',
    '超小屏': 'Extra Small',
    '字重': 'Font Weight',
    '页面标题': 'Page Title',
    '间距系统': 'Spacing System',
    '基础间距': 'Base Spacing',
    '级别': 'Level',
    '紧凑元素内间距': 'Compact element inner spacing',
    '列表项间距': 'List item spacing',
    '卡片内间距': 'Card inner spacing',
    '区块间距': 'Section spacing',
    '大区块间距': 'Large section spacing',
    '页面级间距': 'Page-level spacing',
    '分类区块间距': 'Category section spacing',
    '容器内边距': 'Container Padding',
    '页面容器': 'Page container',
    '卡片': 'Card',
    '区域': 'Area',
    '圆角系统': 'Border Radius System',
    '圆角值': 'Radius Value',
    '按钮': 'Button',
    '标签': 'Tag',
    '图片': 'Image',
    '底部': 'Bottom',
    '桌面': 'Desktop',
    '移动': 'Mobile',
    '相关文章区域': 'Related articles area',
    '阴影系统': 'Shadow System',
    '场景': 'Scenario',
    '阴影值': 'Shadow Value',
    '卡片默认': 'Card default',
    '卡片悬停': 'Card hover',
    '按钮悬停': 'Button hover',
    '按钮': 'Button',
    '标签悬停': 'Tag hover',
    '组件设计规范': 'Component Design Specification',
    '主按钮': 'Primary Button',
    '背景': 'Background',
    '主渐变': 'Primary gradient',
    '文字': 'Text',
    '白色': 'White',
    '边框': 'Border',
    '圆角': 'Border radius',
    '最小高度': 'Minimum height',
    '触控友好': 'Touch friendly',
    '上移': 'Move up',
    '阴影': 'Shadow',
    '次按钮': 'Secondary Button',
    '透明': 'Transparent',
    '亮': 'Light',
    '暗': 'Dark',
    '品牌色': 'Brand color',
    '填充背景': 'Fill background',
    '文字反色': 'Invert text color',
    '统计卡片': 'Stat Card',
    '列网格': 'Column grid',
    '桌面': 'Desktop',
    '平板': 'Tablet',
    '移动': 'Mobile',
    '数字': 'Number',
    '渐变色文字': 'Gradient text',
    '字号': 'Font size',
    '超小': 'Extra small',
    '上移': 'Move up',
    '品牌色阴影': 'Brand color shadow',
    '平台卡片': 'Platform Card',
    '列网格': 'Column grid',
    '尺寸': 'Size',
    '最小高度': 'Minimum height',
    '上移': 'Move up',
    '品牌色阴影': 'Brand color shadow',
    '滚动条': 'Scrolling Bar',
    '固定定位': 'Fixed positioning',
    '背景': 'Background',
    '品牌色渐变': 'Brand color gradient',
    '动画': 'Animation',
    '文字': 'Text',
    '白色': 'White',
    '分隔符': 'Separator',
    '半透明白色': 'Semi-transparent white',
    '悬停暂停': 'Pause on hover',
    '两端渐变遮罩': 'Gradient masks on both ends',
    '宽': 'Wide',
    '侧边栏组件': 'Sidebar Components',
    '通用规范': 'General Specification',
    '粘性定位': 'Sticky positioning',
    '白色背景': 'White background',
    '亮': 'Light',
    '暗': 'Dark',
    '圆角': 'Border radius',
    '阴影': 'Shadow',
    '标题底部': 'Title bottom',
    '分隔线': 'Divider line',
    '左侧品牌目录': 'Left Brand Directory',
    '宽度': 'Width',
    '最大高度': 'Maximum height',
    '可滚动': 'Scrollable',
    '自定义滚动条': 'Custom scrollbar',
    '宽': 'Wide',
    '右侧热门交易': 'Right Trending Deals',
    '排名数字': 'Rank number',
    '字重': 'Font weight',
    '品牌色': 'Brand color',
    '徽章': 'Badge',
    '彩色背景': 'Colored background',
    '白色文字': 'White text',
    '圆角': 'Border radius',
    '文章操作按钮': 'Article Action Buttons',
    '居中排列': 'Centered layout',
    '间距': 'Spacing',
    '桌面': 'Desktop',
    '移动': 'Mobile',
    '与标题间距': 'Spacing from title',
    '浮动按钮': 'Floating Button',
    '固定定位': 'Fixed positioning',
    '背景': 'Background',
    '圆角': 'Border radius',
    '悬停': 'Hover',
    '上移': 'Move up',
    '深色背景': 'Dark background',
    '文章索引标签': 'Article Index Tags',
    '边框': 'Border',
    '每个标签独立颜色': 'Each tag has independent color',
    '内间距': 'Inner padding',
    '最小高度': 'Minimum height',
    '上移': 'Move up',
    '阴影': 'Shadow',
    '响应式断点': 'Responsive Breakpoints',
    '断点': 'Breakpoint',
    '宽度': 'Width',
    '主要变化': 'Main Changes',
    '完整三栏布局': 'Full three-column layout',
    '统计': 'Statistics',
    '列': 'Column',
    '平台': 'Platform',
    '单栏布局': 'Single-column layout',
    '隐藏': 'Hide',
    '图片': 'Image',
    '进一步缩小字号和间距': 'Further reduce font size and spacing',
    '动效规范': 'Animation Specification',
    '元素': 'Element',
    '动效': 'Animation',
    '时长': 'Duration',
    '缓动': 'Easing',
    '卡片悬停': 'Card hover',
    '按钮悬停': 'Button hover',
    '阴影变化': 'Shadow transition',
    '过渡': 'Transition',
    '颜色变化': 'Color transition',
    '移动': 'Move',
    '光晕': 'Glow',
    '暗色模式适配': 'Dark Mode Adaptation',
    '所有组件均支持暗色模式': 'All components support dark mode',
    '通过': 'Through',
    '类选择器覆盖': 'class selector override',
    '元素': 'Element',
    '亮色': 'Light',
    '暗色': 'Dark',
    '页面背景': 'Page background',
    '卡片背景': 'Card background',
    '主文本': 'Primary text',
    '次要文本': 'Secondary text',
    '边框': 'Border',
    '品牌链接': 'Brand link',
    '渐变透明度': 'Gradient opacity',
    '无障碍设计': 'Accessibility Design',
    '触控目标': 'Touch target',
    '最小': 'Minimum',
    '颜色对比度': 'Color contrast',
    '符合': 'Compliant with',
    '标准': 'standard',
    '焦点指示': 'Focus indicator',
    '保留浏览器默认焦点样式': 'Keep browser default focus style',
    '语义化': 'Semantic',
    '使用': 'Use',
    '等语义标签': 'and other semantic tags',
    '标签': 'Tags',
    '关键交互元素添加': 'Add to key interactive elements',
    '和': 'and',
    '设计令牌汇总': 'Design Token Summary',
    '可直接复用的设计令牌': 'Directly reusable design tokens',
    '颜色': 'Colors',
    '间距': 'Spacing',
    '圆角': 'Border Radius',
    '阴影': 'Shadows',
    '过渡': 'Transitions',
    '导航高度': 'Navigation Height',

    # ---- 05-SEO实现 ----
    '实现指南': 'Implementation Guide',
    '本文档详细说明了': 'This document details',
    '的': "'s",
    '优化策略和具体实现方式': 'optimization strategy and specific implementation',
    '该项目以': 'This project targets',
    '收录和排名为核心目标': 'indexing and ranking as core goals',
    '同时兼顾联盟审核通过和': 'while also ensuring affiliate approval and',
    '可信度建设': 'credibility building',
    '架构总览': 'Architecture Overview',
    '优化层': 'Optimization Layer',
    '技术': 'Technical',
    '内容': 'Content',
    '分析追踪': 'Analytics Tracking',
    '技术': 'Technical',
    '配置': 'Configuration',
    '关键设计': 'Key Design',
    '使用': 'Use',
    '过滤不需要索引的页面': 'to filter pages that should not be indexed',
    '页面仅作为资源引用': 'page is only used as a resource reference',
    '不应被搜索引擎收录': 'should not be indexed by search engines',
    '自动生成': 'Auto-generate',
    '并在': 'and declare in',
    '中声明': 'declare in',
    '设计要点': 'Design Points',
    '允许所有爬虫抓取': 'Allow all crawlers to crawl',
    '明确声明': 'Explicitly declare',
    '位置': 'location',
    '设置': 'Set',
    '避免服务器过载': 'to avoid server overload',
    '所有路径公开': 'All paths are public',
    '无隐藏内容': 'No hidden content',
    '结构': 'Structure',
    '模式': 'Pattern',
    '页面类型': 'Page Type',
    '示例': 'Example',
    '全局': 'Global',
    '页面级': 'Page-level',
    '页面标题': 'Page title',
    '以内': 'within',
    '描述': 'Description',
    '性能优化': 'Performance Optimization',
    '指标': 'Metric',
    '优化措施': 'Optimization Measures',
    '图片': 'Images',
    '分发': 'Distribution',
    '预加载关键资源': 'Preload critical resources',
    '最小化': 'Minimize',
    '异步加载第三方脚本': 'Async load third-party scripts',
    '固定尺寸图片': 'Fixed-size images',
    '预留广告位空间': 'Reserve ad space',
    '加速动画': 'Accelerated animations',
    '防抖节流事件处理': 'Debounce/throttle event handling',
    '为所有': 'For all',
    '的文章页面自动生成': 'article pages, auto-generate',
    '标记': 'markup',
    '输出示例': 'Output Example',
    '为含': 'For articles with',
    '的文章生成': 'generate',
    '标记': 'markup',
    '更多': 'More',
    '映射': 'Mapping',
    '价值': 'Value',
    '可在搜索结果中展示富文本摘要': 'Can display rich text snippets in search results',
    '提高点击率': 'Improve click-through rate',
    '注入方式': 'Injection Method',
    '所有': 'All',
    '通过': 'through',
    '钩子注入到页面': 'hook injected into page',
    '中': 'in',
    '使用': 'Use',
    '数组将多个': 'array to merge multiple',
    '合并为一个脚本块': 'into one script block',
    '减少': 'Reduce',
    '中的脚本标签数量': 'number of script tags in',
    '保留页面': 'Keep page',
    '中已有的': 'existing',
    '标签': 'tags',
    '规范': 'Specification',
    '规范说明': 'Specification Details',
    '以内': 'within',
    '包含目标关键词': 'Include target keywords',
    '包含关键词和': 'Include keywords and',
    '个相关关键词': 'related keywords',
    '发布日期': 'Publish date',
    '用于': 'Used for',
    '和排序': 'and sorting',
    '是否生成': 'Whether to generate',
    '内容结构': 'Content Structure',
    '引言': 'Introduction',
    '含关键词': 'Include keywords',
    '产品概述': 'Product Overview',
    '详细评测': 'Detailed Review',
    '优缺点分析': 'Pros and Cons Analysis',
    '购买建议': 'Purchase Recommendation',
    '如果': 'If',
    '相关文章': 'Related Articles',
    '内部链接策略': 'Internal Linking Strategy',
    '链接模式': 'Link Pattern',
    '类型': 'Type',
    '位置': 'Location',
    '目标': 'Target',
    '导航链接': 'Navigation links',
    '顶部导航': 'Top navigation',
    '文章链接': 'Article links',
    '文章末尾': 'Article end',
    '侧边栏链接': 'Sidebar links',
    '左': 'Left',
    '右侧边栏': 'Right sidebar',
    '工具': 'Tool',
    '分类链接': 'Category links',
    '索引页': 'Index page',
    '各分类文章': 'Category articles',
    '链接': 'Links',
    '文章标题下': 'Below article title',
    '平台页': 'Platform page',
    '内部链接原则': 'Internal Linking Principles',
    '每篇文章至少': 'Each article at least',
    '个内部链接': 'internal links',
    '使用描述性锚文本': 'Use descriptive anchor text',
    '链接到相关内容': 'Link to related content',
    '避免无关链接': 'Avoid irrelevant links',
    '使用相对路径': 'Use relative paths',
    '可信度建设': 'Credibility Building',
    '维度': 'Dimension',
    '实现方式': 'Implementation',
    '详细的产品评测': 'Detailed product reviews',
    '真实的使用体验': 'Real user experience',
    '专业的行业分析': 'Professional industry analysis',
    '数据支撑的结论': 'Data-supported conclusions',
    '一致的品牌信息': 'Consistent brand information',
    '客观的优缺点分析': 'Objective pros and cons analysis',
    '透明的': 'Transparent',
    '声明': 'Disclosure',
    '联盟营销': 'Affiliate Marketing',
    '链接优化': 'Link Optimization',
    '标准': 'Standard',
    '链接': 'Link',
    '购买链接': 'Purchase link',
    '关键属性': 'Key Attributes',
    '告知搜索引擎这是赞助': 'Inform search engines this is a sponsored',
    '链接': 'link',
    '安全属性': 'Security attributes',
    '新标签页打开': 'Open in new tab',
    '收录优化': 'Indexing Optimization',
    '通过': 'Via',
    '提交': 'Submit',
    '新文章发布后通过': 'After new article publish via',
    '请求索引': 'Request indexing',
    '通过首页和索引页传递链接权重': 'Pass link equity through homepage and index pages',
    '提高收录质量': 'Improve indexing quality',
    '标签隐藏策略': 'Tag Hiding Strategy',
    '为保持页面整洁': 'To keep pages clean',
    '同时保留': 'while preserving',
    '价值': 'value',
    '标签使用视觉隐藏方式': 'tags use visual hiding method',
    '设计意图': 'Design Intent',
    '标签内容保留在': 'Tag content preserved in',
    '中': 'in',
    '搜索引擎可抓取': 'search engines can crawl',
    '视觉上不可见': 'Visually invisible',
    '不影响用户体验': 'Does not affect user experience',
    '比': 'Than',
    '更安全': 'safer',
    '某些搜索引擎可能忽略': 'some search engines may ignore',
    '的内容': 'content',
    '分析追踪': 'Analytics Tracking',
    '追踪配置': 'Tracking Configuration',
    '首页路径映射为': 'Homepage path mapped to',
    '区分首页和其他页面': 'Distinguish homepage from other pages',
    '自动追踪页面浏览': 'Auto-track page views',
    '支持自定义事件追踪': 'Support custom event tracking',
    '关键追踪指标': 'Key Tracking Metrics',
    '说明': 'Description',
    '目标': 'Target',
    '页面浏览量': 'Page views',
    '总流量': 'Total traffic',
    '持续增长': 'Continuous growth',
    '跳出率': 'Bounce rate',
    '单页访问比例': 'Single-page visit ratio',
    '平均停留时间': 'Average time on page',
    '用户参与度': 'User engagement',
    '分钟': 'minutes',
    '点击率': 'Click-through rate',
    '转化效果': 'Conversion effect',
    '自然搜索流量': 'Organic search traffic',
    '效果': 'Effect',
    '占比': 'Proportion',
    '检查清单': 'Checklist',
    '新文章发布前检查': 'Pre-Publish Checklist',
    '包含目标关键词': 'Include target keywords',
    '字符以内': 'characters within',
    '字符': 'characters',
    '包含关键词和': 'Include keywords and',
    '个相关关键词': 'related keywords',
    '至少': 'At least',
    '张封面图': 'cover image',
    '带': 'with',
    '文本': 'text',
    '至少': 'At least',
    '个内部链接': 'internal links',
    '使用': 'Use',
    '组织内容结构': 'to organize content structure',
    '文章字数': 'Article word count',
    '大于': 'greater than',
    '完整': 'Complete',
    '如有': 'If has',
    '设置': 'Set',
    '在': 'In',
    '中添加分类条目': 'add category entry',
    '构建后检查': 'After build check',
    '包含新页面': 'includes new page',
    '月度': 'Monthly',
    '维护': 'Maintenance',
    '检查': 'Check',
    '错误': 'errors',
    '查看': 'View',
    '流量趋势': 'Traffic trends',
    '更新过期内容': 'Update expired content',
    '检查死链': 'Check dead links',
    '提交新': 'Submit new',

    # ---- 06-关键功能实现 ----
    '关键功能实现文档': 'Key Features Implementation Document',
    '本文档详细说明了': 'This document details',
    '中各关键功能的实现方式': "each key feature's implementation",
    '包含完整的代码示例和设计思路': 'including complete code examples and design rationale',
    '每个功能都经过精心设计': 'Each feature is carefully designed',
    '兼顾用户体验': 'balancing user experience',
    '效果和转化率优化': 'effects and conversion rate optimization',
    '功能说明': 'Feature Description',
    '固定在页面顶部的滚动公告栏': 'Fixed scrolling banner at the top of the page',
    '展示全球用户下单信息': 'Displays global user order information',
    '营造社会证明效果': 'Creates social proof effect',
    '实现文件': 'Implementation Files',
    '数据定义和渲染逻辑': 'Data definition and rendering logic',
    '样式和动画': 'Styles and animations',
    '核心代码': 'Core Code',
    '数据定义': 'Data Definition',
    '个国家': 'countries',
    '地区': 'regions',
    '渲染注入': 'Render Injection',
    '动画': 'Animation',
    '无缝循环': 'Seamless Loop',
    '内容重复两次': 'Content repeated twice',
    '动画移动': 'Animation moves',
    '实现无缝衔接': 'to achieve seamless connection',
    '性能优化': 'Performance Optimization',
    '启用': 'Enable',
    '加速': 'acceleration',
    '悬停暂停': 'Pause on hover',
    '用户可暂停阅读': 'Users can pause to read',
    '两端遮罩': 'Gradient masks on both ends',
    '使用': 'Use',
    '和': 'and',
    '伪元素创建渐变遮罩': 'pseudo-elements to create gradient masks',
    '导航栏偏移': 'Navigation bar offset',
    '固定后': 'After fixed',
    '导航栏和内容区域相应下移': 'Navigation bar and content area shift down accordingly',
    '偏移处理': 'Offset Handling',
    '高度': 'Height',
    '为固定元素预留空间': 'Reserve space for fixed elements',
    '在每篇文档页面的': 'On each document page',
    '标题下方自动注入两个': 'automatically inject two',
    '按钮': 'buttons',
    '函数': 'Function',
    '注入逻辑': 'Injection logic',
    '防止重复注入': 'Prevent duplicate injection',
    '类是否已存在': 'class already exists',
    '初始加载': 'Initial load',
    '导航监听': 'Navigation monitoring',
    '监听': 'Monitor',
    '变化': 'changes',
    '自动在': 'Automatically after',
    '导航后重新注入': 'navigation re-inject',
    '检查': 'Check',
    '类是否已存在': 'class already exists',
    '兼容': 'Compatible',
    '检查': 'Check',
    '无障碍': 'Accessibility',
    '添加': 'Add',
    '和': 'and',
    '样式': 'Style',
    '居中排列': 'Centered layout',
    '响应式间距': 'Responsive spacing',
    '按钮样式': 'Button Styles',
    '拦截': 'Intercept',
    '首页': 'Homepage',
    '区域的': "'s",
    '将默认链接行为替换为': 'Replace default link behavior with',
    '控制的': 'controlled',
    '函数': 'Function',
    '双场景覆盖': 'Dual Scenario Coverage',
    '同时处理初始加载和': 'Handle both initial load and',
    '导航': 'navigation',
    '延迟执行': 'Delayed Execution',
    '导航后': 'After navigation',
    '等待': 'Wait for',
    '渲染': 'rendering',
    '属性替换': 'Attribute Replacement',
    '移除': 'Remove',
    '防止默认行为': 'to prevent default behavior',
    '添加': 'Add',
    '保持语义': 'to maintain semantics',
    '文本匹配': 'Text Matching',
    '通过按钮文本内容识别目标按钮': 'Identify target button by text content',
    '文章页面采用三栏布局': 'Article pages use three-column layout',
    '左侧品牌目录': 'Left brand directory',
    '中间主内容': 'Middle main content',
    '右侧热门交易': 'Right trending deals',
    '布局组件': 'Layout Component',
    '左侧品牌目录': 'Left Brand Directory',
    '右侧热门交易': 'Right Trending Deals',
    '中间自适应': 'Middle adaptive',
    '两侧边栏': 'Both sidebars',
    '以下切换为单栏': 'Below switches to single column',
    '品牌目录和热门交易通过数据数组渲染': 'Brand directory and trending deals rendered through data arrays',
    '所有链接指向': 'All links point to',
    '最大化转化机会': 'Maximize conversion opportunities',
    '分类展示所有文章': 'Categorically display all articles',
    '支持多维度筛选': 'Support multi-dimensional filtering',
    '分类数据结构': 'Category Data Structure',
    '未来可扩展': 'Future extensible',
    '等维度': 'dimensions',
    '新增分类只需在': 'Adding new categories only requires',
    '数组中添加对象': 'adding objects to array',
    '彩色标签': 'Colorful tags',
    '每个标签有独立颜色': 'Each tag has independent color',
    '通过': 'Through',
    '绑定': 'binding',
    '两栏布局': 'Two-column layout',
    '主内容区': 'Main content area',
    '右侧快速链接侧边栏': 'Right quick links sidebar',
    '移动端横滑': 'Mobile horizontal scroll',
    '标签在移动端支持横向滚动': 'Tags support horizontal scrolling on mobile',
    '固定在页面右下角的': 'Fixed at bottom-right of page',
    '社区邀请按钮': 'Community invitation button',
    '函数': 'Function',
    '插槽': 'Slot',
    '左侧垂直滚动的品牌名称列表': 'Left vertical scrolling brand name list',
    '点击可跳转到': 'Click to navigate to',
    '垂直无缝滚动': 'Vertical seamless scrolling',
    '与顶部': 'Similar to top',
    '类似的原理': 'similar principle',
    '但方向为垂直': 'but direction is vertical',
    '上下遮罩': 'Top and bottom masks',
    '使用渐变遮罩实现淡入淡出效果': 'Use gradient masks for fade in/out effect',
    '整体可点击': 'Entire container clickable',
    '整个容器可点击跳转到': 'Entire container clickable to navigate to',
    '品牌列表': 'Brand list',
    '个热门品牌': 'popular brands',
    '重复渲染实现循环': 'Repeated rendering for loop',
    '首页': 'Homepage',
    '区域': 'Area',
    '采用左文右图布局': 'Uses left-text-right-image layout',
    '包含统计数据展示': 'Includes statistics display',
    '配置': 'Configuration',
    '统计数据展示': 'Statistics Display',
    '响应式策略': 'Responsive Strategy',
    '桌面': 'Desktop',
    '左文右图': 'Left text right image',
    '列统计卡片': 'Column stat cards',
    '平板': 'Tablet',
    '左文右图': 'Left text right image',
    '图片缩小': 'Image shrunk',
    '列统计': 'Column stats',
    '移动': 'Mobile',
    '隐藏图片': 'Hide image',
    '纯文字堆叠': 'Text only stacked',
    '列统计': 'Column stats',
    '超小': 'Extra small',
    '进一步缩小字号和间距': 'Further reduce font size and spacing',

    # ---- 07-部署指南 ----
    '部署指南': 'Deployment Guide',
    '本文档说明了': 'This document describes',
    '的部署流程': "'s deployment process",
    '环境配置和运维监控': 'environment configuration and operations monitoring',
    '项目使用': 'The project uses',
    '进行静态站点部署': 'for static site deployment',
    '通过': 'Through',
    '推送自动触发构建和部署': 'push auto-triggers build and deployment',
    '部署架构': 'Deployment Architecture',
    '本地开发': 'Local Development',
    '推送': 'Push',
    '用户访问': 'User Access',
    '环境准备': 'Environment Preparation',
    '本地开发环境': 'Local Development Environment',
    '必需': 'Required',
    '安装步骤': 'Installation Steps',
    '克隆仓库': 'Clone repository',
    '安装依赖': 'Install dependencies',
    '启动开发服务器': 'Start development server',
    '项目配置': 'Project Configuration',
    '初始设置': 'Initial Setup',
    '登录': 'Login',
    '进入': 'Go to',
    '选择': 'Select',
    '连接': 'Connect',
    '选择': 'Select',
    '仓库': 'Repository',
    '配置构建设置': 'Configure build settings',
    '构建配置': 'Build Configuration',
    '配置项': 'Configuration Item',
    '值': 'Value',
    '框架预设': 'Framework Preset',
    '构建命令': 'Build Command',
    '构建输出目录': 'Build Output Directory',
    '根目录': 'Root Directory',
    '版本': 'Version',
    '环境变量': 'Environment Variables',
    '自定义域名': 'Custom Domain',
    '进入项目': 'Go to project',
    '设置域名': 'Set up a domain',
    '输入域名': 'Enter domain',
    '自动创建': 'Auto-create',
    '记录': 'records',
    '等待': 'Wait for',
    '证书签发': 'certificate issuance',
    '通常几分钟': 'Usually a few minutes',
    '分支部署策略': 'Branch Deployment Strategy',
    '分支': 'Branch',
    '部署目标': 'Deployment Target',
    '用途': 'Purpose',
    '生产环境': 'Production',
    '正式发布': 'Official release',
    '预览环境': 'Preview',
    '开发测试': 'Development testing',
    '功能开发': 'Feature development',
    '部署流程': 'Deployment Process',
    '标准发布流程': 'Standard Release Process',
    '本地开发和测试': 'Local development and testing',
    '构建验证': 'Build verification',
    '提交代码': 'Submit code',
    '推送到仓库': 'Push to repository',
    '推送后': 'After push',
    '自动触发构建和部署': 'Auto-triggers build and deployment',
    '通常': 'Usually',
    '分钟完成': 'minutes to complete',
    '构建输出': 'Build Output',
    '打包后的': 'Bundled',
    '优化后的图片': 'Optimized images',
    '部署验证': 'Deployment Verification',
    '部署完成后检查': 'Check after deployment',
    '页面可访问性': 'Page accessibility',
    '访问': 'Visit',
    '检查': 'Check',
    '新页面': 'New page',
    '确认新文章页面可正常访问': 'Confirm new article page is accessible',
    '在': 'In',
    '中确认数据接收': 'confirm data reception',
    '移动端': 'Mobile',
    '检查响应式布局': 'Check responsive layout',
    '本地构建与预览': 'Local Build and Preview',
    '开发模式': 'Development Mode',
    '热更新': 'Hot reload',
    '修改文件后自动刷新': 'Auto-refresh after file modification',
    '默认端口': 'Default port',
    '生产构建': 'Production Build',
    '输出目录': 'Output directory',
    '资源目录': 'Asset directory',
    '自动优化': 'Auto optimization',
    '代码压缩': 'Code compression',
    '图片优化': 'Image optimization',
    '本地预览': 'Local Preview',
    '预览构建结果': 'Preview build result',
    '监控与分析': 'Monitoring & Analytics',
    '关键指标': 'Key Metrics',
    '说明': 'Description',
    '查看位置': 'View Location',
    '用户数': 'Users',
    '独立访客': 'Unique visitors',
    '页面浏览量': 'Page views',
    '总': 'Total',
    '跳出率': 'Bounce rate',
    '单页访问比例': 'Single-page visit ratio',
    '平均停留时间': 'Average time on page',
    '用户参与度': 'User engagement',
    '流量来源': 'Traffic source',
    '自然搜索': 'Organic search',
    '直接': 'Direct',
    '推荐': 'Referral',
    '关键操作': 'Key Operations',
    '提交': 'Submit',
    '请求索引': 'Request indexing',
    '新文章发布后手动请求': 'Manually request after new article publish',
    '检查错误': 'Check errors',
    '查看表现': 'View performance',
    '查看位置': 'View Location',
    '请求数': 'Requests',
    '总请求量': 'Total requests',
    '带宽': 'Bandwidth',
    '流量消耗': 'Traffic consumption',
    '缓存命中率': 'Cache hit rate',
    '效率': 'Efficiency',
    '威胁评分': 'Threat score',
    '安全状况': 'Security status',
    '页面加载时间': 'Page load time',
    '性能指标': 'Performance metrics',
    '故障排查': 'Troubleshooting',
    '构建失败': 'Build Failure',
    '常见原因': 'Common Causes',
    '版本不兼容': 'Version incompatible',
    '检查': 'Check',
    '环境变量': 'environment variable',
    '依赖安装失败': 'Dependency installation failed',
    '检查': 'Check',
    '格式': 'format',
    '语法错误': 'Syntax error',
    '检查': 'Check',
    '格式': 'format',
    '死链': 'Dead links',
    '设置': 'Set',
    '已配置': 'Already configured',
    '排查步骤': 'Troubleshooting Steps',
    '本地构建测试': 'Local build test',
    '查看详细错误日志': 'View detailed error logs',
    '查看构建日志': 'View build logs',
    '页面': 'Page',
    '排查步骤': 'Troubleshooting Steps',
    '检查': 'Check',
    '是否正确': 'is correct',
    '模式': 'mode',
    '确认': 'Confirm',
    '文件存在': 'file exists',
    '检查': 'Check',
    '中的': 'in',
    '清除': 'Clear',
    '缓存': 'cache',
    '样式异常': 'Style Issues',
    '排查步骤': 'Troubleshooting Steps',
    '检查': 'Check',
    '是否有语法错误': 'has syntax errors',
    '确认': 'Confirm',
    '使用正确': 'used correctly',
    '清除浏览器缓存': 'Clear browser cache',
    '检查暗色模式下的样式覆盖': 'Check dark mode style overrides',
    '问题': 'Issues',
    '排查步骤': 'Troubleshooting Steps',
    '使用': 'Use',
    '检查结构化数据': 'to check structured data',
    '使用': 'Use',
    '检查': 'to check',
    '评分': 'score',
    '检查': 'Check',
    '和': 'and',
    '在': 'In',
    '中查看索引状态': 'check index status',
    '缓存管理': 'Cache Management',
    '缓存': 'Cache',
    '清除缓存': 'Clear Cache',
    '选择': 'Select',
    '或指定': 'or specify',
    '缓存规则': 'Cache Rules',
    '静态资源': 'Static assets',
    '自动缓存': 'Auto-cache',
    '页面': 'Pages',
    '默认不缓存': 'Not cached by default',
    '边缘': 'Edge',
    '请求': 'Requests',
    '不缓存': 'Not cached',
    '浏览器缓存': 'Browser Cache',
    '构建时自动处理': 'Auto-handled during build',
    '带': 'With',
    '的资源文件名': 'resource filenames',
    '长期缓存': 'Long-term cache',
    '文件': 'Files',
    '不缓存': 'Not cached',
    '始终获取最新版本': 'Always get latest version',
    '安全配置': 'Security Configuration',
    '自动提供': 'Auto-provide',
    '证书': 'certificate',
    '无需额外配置': 'No extra configuration needed',
    '安全头': 'Security Headers',
    '默认添加以下安全头': 'Default adds the following security headers',
    '防护': 'Protection',
    '自动提供': 'Auto-provide',
    '防护': 'protection',
    '无需额外配置': 'No extra configuration needed',
    '性能优化清单': 'Performance Optimization Checklist',
    '部署前': 'Before Deployment',
    '运行': 'Run',
    '确认构建成功': 'Confirm build success',
    '运行': 'Run',
    '检查页面': 'Check pages',
    '使用': 'Use',
    '检查性能评分': 'Check performance score',
    '压缩所有图片': 'Compress all images',
    '格式': 'Format',
    '检查所有链接是否有效': 'Check all links are valid',
    '部署后': 'After Deployment',
    '验证页面可访问性': 'Verify page accessibility',
    '检查': 'Check',
    '数据接收': 'data reception',
    '在': 'In',
    '提交新': 'Submit new',
    '检查移动端显示效果': 'Check mobile display',
    '测试': 'Test',
    '按钮链接': 'button links',
    '版本回滚': 'Version Rollback',
    '如需回滚到之前的部署版本': 'To rollback to a previous deployment version',
    '找到目标部署版本': 'Find target deployment version',
    '点击': 'Click',
    '按钮': 'button',
    '确认回滚': 'Confirm rollback',

    # ---- 08-内容模型 ----
    '内容模型文档': 'Content Model Document',
    '本文档定义了': 'This document defines',
    '的内容结构和数据模型': "'s content structure and data model",
    '所有内容使用': 'All content uses',
    '文件管理': 'file management',
    '通过': 'Through',
    '定义元数据': 'define metadata',
    '内容类型': 'Content Types',
    '文件': 'File',
    '正文内容': 'Body Content',
    '格式的补充内容': 'formatted supplementary content',
    '统计数据': 'statistics',
    '优势介绍等': 'advantages, etc.',
    '文章页': 'Article Page',
    '文章标题': 'Article title',
    '以内': 'within',
    '含关键词': 'Include keywords',
    '描述': 'Description',
    '含关键词和': 'Include keywords and',
    '正文结构': 'Body Structure',
    '概述文章内容': 'Overview article content',
    '包含目标关键词': 'Include target keywords',
    '主要内容': 'Main Content',
    '子主题': 'Subtopic',
    '总结': 'Summary',
    '购买建议': 'Purchase Recommendation',
    '相关文章': 'Related Articles',
    '平台页': 'Platform Page',
    '正文内容': 'Body Content',
    '平台对比卡片': 'Platform comparison cards',
    '格式': 'Format',
    '文章索引页': 'Article Index Page',
    '渲染': 'Rendering',
    '由': 'By',
    '组件渲染': 'component rendering',
    '无需正文内容': 'No body content needed',
    '媒体资源页': 'Media Resource Page',
    '或': 'or',
    '用途': 'Purpose',
    '存放媒体资源引用': 'Store media resource references',
    '不面向用户': 'Not user-facing',
    '在': 'In',
    '中被排除': 'excluded from',
    '页面': 'Page',
    '文件': 'File',
    '用途': 'Purpose',
    '自定义': 'Custom',
    '错误页面': 'Error page',
    '字段规范': 'Field Specification',
    '通用字段': 'General Fields',
    '字段': 'Field',
    '类型': 'Type',
    '必需': 'Required',
    '页面布局': 'Page layout',
    '页面标题': 'Page title',
    '字符以内': 'characters within',
    '描述': 'Description',
    '字符': 'characters',
    '逗号分隔的关键词': 'Comma-separated keywords',
    '文章专用字段': 'Article-Specific Fields',
    '发布日期': 'Publish date',
    '作者名称': 'Author name',
    '标签数组': 'Tag array',
    '是否生成': 'Whether to generate',
    '首页专用字段': 'Homepage-Specific Fields',
    '区域配置': 'Area configuration',
    '特性卡片数组': 'Feature card array',
    '内容目录结构': 'Content Directory Structure',
    '文章目录': 'Article Directory',
    '文章索引': 'Article Index',
    '平台评测': 'Platform Review',
    '产品评测': 'Product Review',
    '文章正文': 'Article body',
    '媒体资源': 'Media resources',
    '季节穿搭': 'Seasonal Style',
    '静态资源': 'Static Assets',
    '网站图标': 'Website icon',
    '爬虫规则': 'Crawler rules',
    '图片资源': 'Image resources',
    '文章封面图': 'Article cover images',
    '文章类型分类': 'Article Type Classification',
    '路径模式': 'Path Pattern',
    '内容结构': 'Content Structure',
    '平台概述': 'Platform overview',
    '功能特点': 'Feature highlights',
    '费用结构': 'Fee structure',
    '使用教程': 'Usage tutorial',
    '优缺点分析': 'Pros and cons analysis',
    '与其他平台对比': 'Comparison with other platforms',
    '产品概述': 'Product overview',
    '设计和材质': 'Design and materials',
    '尺码和合身度': 'Sizing and fit',
    '穿搭建议': 'Styling advice',
    '性价比分析': 'Value analysis',
    '购买渠道推荐': 'Purchase channel recommendations',
    '季节趋势概述': 'Seasonal trend overview',
    '必备单品推荐': 'Essential items recommendation',
    '穿搭技巧': 'Styling tips',
    '品牌推荐': 'Brand recommendations',
    '购买链接': 'Purchase links',
    '工具概述': 'Tool overview',
    '功能介绍': 'Feature introduction',
    '使用方法': 'Usage method',
    '下载': 'Download',
    '访问链接': 'Access link',
    '图片资源规范': 'Image Resource Specification',
    '封面图片': 'Cover Image',
    '路径': 'Path',
    '规范': 'Specification',
    '尺寸': 'Size',
    '建议': 'Recommended',
    '或': 'or',
    '文件大小': 'File size',
    '小于': 'Less than',
    '文本': 'Text',
    '描述性文本': 'Descriptive text',
    '包含关键词': 'Include keywords',
    '平台': 'Platform',
    '尺寸': 'Size',
    '背景': 'Background',
    '透明或白色': 'Transparent or white',
    '小于': 'Less than',
    '媒体资源图': 'Media Resource Images',
    '路径': 'Path',
    '保留质量': 'Preserve quality',
    '用途': 'Purpose',
    '文章内嵌图片': 'Article embedded images',
    '小于': 'Less than',
    '内容创作规范': 'Content Creation Specification',
    '标题规范': 'Title Specification',
    '包含目标关键词': 'Include target keywords',
    '字符以内': 'characters within',
    '使用': 'Use',
    '包含数字或行动词更佳': 'Including numbers or action verbs is better',
    '示例': 'Example',
    '描述规范': 'Description Specification',
    '字符': 'characters',
    '包含主要关键词': 'Include primary keywords',
    '包含行动召唤': 'Include call to action',
    '概括文章核心价值': 'Summarize article core value',
    '关键词规范': 'Keyword Specification',
    '个关键词': 'keywords',
    '逗号分隔': 'Comma-separated',
    '包含主要关键词和长尾关键词': 'Include primary and long-tail keywords',
    '与文章内容高度相关': 'Highly relevant to article content',
    '正文规范': 'Body Specification',
    '最少': 'Minimum',
    '字': 'words',
    '使用': 'Use',
    '组织结构': 'to organize structure',
    '每段不超过': 'Each paragraph no more than',
    '行': 'lines',
    '包含内部链接': 'Include internal links',
    '至少': 'At least',
    '个': '',
    '包含外部链接': 'Include external links',
    '权威来源': 'Authoritative sources',
    '图片使用': 'Images use',
    '文本': 'text',
    '组件数据模型': 'Component Data Model',
    '分类名称': 'Category name',
    '图标': 'Icon',
    '品牌名称': 'Brand name',
    '产品数量': 'Product count',
    '排名': 'Rank',
    '产品名称': 'Product name',
    '徽章文本': 'Badge text',
    '徽章颜色': 'Badge color',
    '统计数据文本': 'Statistics text',
    '统计图标': 'Statistics icon',
    '分类标签': 'Category label',
    '项目名称': 'Item name',
    '图标': 'Icon',
    '链接': 'Link',
    '标签颜色': 'Tag color',
    '滚动文本': 'Scrolling text',
    '品牌名称数组': 'Brand name array',
    '路由映射': 'Route Mapping',
    '文件路径': 'File Path',
    '路由': 'Route',
    '规则': 'Rule',
    '目录下的': "Directory's",
    '映射为目录路径': 'mapped to directory path',

    # ---- 09-API接口 ----
    '接口文档': 'API Documentation',
    '本文档说明了': 'This document describes',
    '的外部集成和': "'s external integration and",
    '该项目作为静态站点': 'This project as a static site',
    '主要通过外部链接和第三方脚本实现集成': 'mainly integrates through external links and third-party scripts',
    '外部集成总览': 'External Integration Overview',
    '集成方式': 'Integration Method',
    '通过外部链接集成': 'Integrated via external links',
    '所有': 'All',
    '按钮指向': 'buttons point to',
    '使用位置': 'Usage Locations',
    '组件': 'Component',
    '用途': 'Purpose',
    '打开方式': 'Open Method',
    '主': 'Primary',
    '新标签': 'New tab',
    '文章页': 'Article page',
    '品牌浏览': 'Brand browsing',
    '交易浏览': 'Deal browsing',
    '品牌快速访问': 'Brand quick access',
    '新标签': 'New tab',
    '链接拦截实现': 'Link Interception Implementation',
    '按钮通过': 'Button through',
    '拦截': 'Interception',
    '安全属性': 'Security Attributes',
    '所有外部链接添加以下属性': 'All external links add the following attributes',
    '防止新页面通过': 'Prevent new page from accessing original page via',
    '访问原页面': 'accessing original page',
    '不发送': 'Do not send',
    '头': 'header',
    '追踪': 'Tracking',
    '通过在': 'By injecting in',
    '中注入': 'inject in',
    '脚本实现': 'script implementation',
    '配置代码': 'Configuration Code',
    '自定义配置': 'Custom Configuration',
    '参数': 'Parameter',
    '值': 'Value',
    '动态计算': 'Dynamically calculated',
    '首页映射为': 'Homepage mapped to',
    '自动追踪事件': 'Auto-Tracked Events',
    '自动追踪以下事件': 'Automatically tracks the following events',
    '事件': 'Event',
    '页面浏览': 'Page view',
    '首次访问': 'First visit',
    '会话开始': 'Session start',
    '自定义事件': 'Custom Events',
    '可扩展': 'Extensible',
    '可通过': 'Can use',
    '函数发送自定义事件': 'function to send custom events',
    '示例': 'Example',
    '追踪': 'Track',
    '点击': 'click',
    '参考': 'Reference',
    '前端事件追踪': 'Frontend event tracking',
    '文档': 'Documentation',
    '后端数据查询': 'Backend data query',
    '邀请链接': 'Invitation Link',
    '通过页面右下角浮动按钮集成': 'Integrated via floating button at bottom-right of page',
    '实现代码': 'Implementation Code',
    '函数': 'Function',
    '插槽': 'Slot',
    '可选扩展': 'Optional Extension',
    '如需在页面中嵌入': 'If you need to embed in page',
    '在线成员数': 'online member count',
    '可使用': 'can use',
    '链接规范': 'Link Specification',
    '链接属性': 'Link Attributes',
    '所有': 'All',
    '链接必须包含以下属性': 'links must include the following attributes',
    '属性': 'Attribute',
    '新标签页打开': 'Open in new tab',
    '安全属性': 'Security attribute',
    '不发送': 'Do not send',
    '告知搜索引擎这是赞助链接': 'Inform search engines this is a sponsored link',
    '链接管理': 'Link Management',
    '当前': 'Current',
    '链接': 'Links',
    '各平台': 'Each platform',
    '链接': 'Links',
    '通过': 'Via',
    '页面管理': 'page management',
    '链接追踪': 'Link Tracking',
    '点击可通过': 'Clicks can be tracked via',
    '自定义事件追踪': 'custom event tracking',
    '示例': 'Example',
    '追踪': 'Track',
    '链接点击': 'link click',
    '搜索引擎集成': 'Search Engine Integration',
    '操作': 'Operations',
    '提交': 'Submit',
    '请求索引': 'Request indexing',
    '通过': 'Via',
    '工具': 'tool',
    '监控表现': 'Monitor performance',
    '可选扩展': 'Optional Extension',
    '请求': 'Request',
    '索引': 'Index',
    '移除': 'Removal',
    '获取搜索表现数据': 'Get search performance data',
    '格式': 'Format',
    '输出格式': 'Output Format',
    '所有结构化数据通过': 'All structured data via',
    '标签输出': 'tag output',
    '文章标题': 'Article title',
    '文章描述': 'Article description',
    '问题文本': 'Question text',
    '答案文本': 'Answer text',
    '验证工具': 'Validation Tools',
    '工具': 'Tool',
    '用途': 'Purpose',
    '验证结构化数据': 'Validate structured data',
    '验证': 'Validate',
    '格式': 'Format',
    '可选扩展': 'Optional Extension',
    '部署': 'Deployment',
    '通过': 'Via',
    '触发部署': 'trigger deployment',
    '缓存清除': 'Cache Purge',
    '清除缓存': 'Clear cache',
    '第三方脚本': 'Third-Party Scripts',
    '已集成的第三方脚本': 'Integrated Third-Party Scripts',
    '脚本': 'Script',
    '来源': 'Source',
    '加载方式': 'Load Method',
    '用途': 'Purpose',
    '追踪': 'Tracking',
    '可扩展的第三方脚本': 'Extensible Third-Party Scripts',
    '搜索功能': 'Search function',
    '标签': 'Tag',
    '评论系统': 'Comment system',
    '用户行为分析': 'User behavior analysis',
    '脚本加载最佳实践': 'Script Loading Best Practices',
    '使用': 'Use',
    '或': 'or',
    '属性': 'attributes',
    '不阻塞页面渲染': 'Do not block page rendering',
    '在': 'In',
    '的': "'s",
    '中统一管理': 'centrally manage',
    '定期审查第三方脚本性能影响': 'Regularly review third-party script performance impact',
    '数据流图': 'Data Flow Diagram',
    '用户访问页面': 'User visits page',
    '渲染': 'Render',
    '注入': 'Inject',
    '结构化数据': 'Structured data',
    '注入': 'Inject',
    '脚本': 'script',
    '浏览器加载页面': 'Browser loads page',
    '发送': 'Send',
    '事件': 'event',
    '用户点击': 'User clicks',
    '用户在': 'User in',
    '中操作': 'operates',
    '可选': 'Optional',
    '用户加入': 'User joins',
    '社区': 'community',

    # ---- Keyword Stats CSV ----
    '所有': 'All',
    '高': 'High',
    '低': 'Low',
    '2025年7月1日 - 2026年6月30日': 'July 1, 2025 - June 30, 2026',
}

# ============================================================
# File-specific translations
# ============================================================

def translate_file(filepath):
    """Read file, translate all Chinese text, write back"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    original = content

    # Sort by length (longer phrases first) to avoid partial replacements
    sorted_keys = sorted(TRANSLATIONS.keys(), key=len, reverse=True)

    for key in sorted_keys:
        content = content.replace(key, TRANSLATIONS[key])

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  Translated: {filepath}")
        return True
    return False


def translate_csv_file(filepath):
    """Translate the Keyword Stats CSV file"""
    # Try multiple encodings
    for enc in ['utf-16', 'utf-16-le', 'utf-8-sig', 'utf-8']:
        try:
            with open(filepath, 'r', encoding=enc) as f:
                lines = f.readlines()
            break
        except (UnicodeDecodeError, LookupError):
            continue

    csv_translations = {
        '所有': 'All',
        '高': 'High',
        '低': 'Low',
        '2025年7月1日 - 2026年6月30日': 'July 1, 2025 - June 30, 2026',
    }

    new_lines = []
    for line in lines:
        for key, val in csv_translations.items():
            line = line.replace(key, val)
        new_lines.append(line)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    print(f"  Translated CSV: {filepath}")


def rename_directories():
    """Rename Chinese directory names to English"""
    main_dir = os.path.join(BASE, 'main')

    renames = {
        '01-技术选型说明': '01-Technology-Selection',
        '02-项目架构': '02-Project-Architecture',
        '03-源代码': '03-Source-Code',
        '04-设计规范': '04-Design-Specification',
        '05-SEO实现': '05-SEO-Implementation',
        '06-关键功能实现': '06-Key-Features',
        '07-部署指南': '07-Deployment-Guide',
        '08-内容模型': '08-Content-Model',
        '09-API接口': '09-API-Interface',
    }

    for old_name, new_name in renames.items():
        old_path = os.path.join(main_dir, old_name)
        new_path = os.path.join(main_dir, new_name)
        if os.path.exists(old_path):
            os.rename(old_path, new_path)
            print(f"  Renamed: {old_name} -> {new_name}")

    # Rename files inside directories
    file_renames = {
        os.path.join(main_dir, '01-Technology-Selection', '技术选型说明.md'): 'Technology-Selection.md',
        os.path.join(main_dir, '02-Project-Architecture', '项目架构.md'): 'Project-Architecture.md',
        os.path.join(main_dir, '04-Design-Specification', '设计规范.md'): 'Design-Specification.md',
        os.path.join(main_dir, '05-SEO-Implementation', 'SEO实现指南.md'): 'SEO-Implementation-Guide.md',
        os.path.join(main_dir, '06-Key-Features', '关键功能实现.md'): 'Key-Features-Implementation.md',
        os.path.join(main_dir, '07-Deployment-Guide', '部署指南.md'): 'Deployment-Guide.md',
        os.path.join(main_dir, '08-Content-Model', '内容模型.md'): 'Content-Model.md',
        os.path.join(main_dir, '09-API-Interface', 'API接口.md'): 'API-Interface.md',
    }

    for old_path, new_name in file_renames.items():
        if os.path.exists(old_path):
            new_path = os.path.join(os.path.dirname(old_path), new_name)
            os.rename(old_path, new_path)
            print(f"  Renamed file: {os.path.basename(old_path)} -> {new_name}")


def fix_custom_css():
    """Fix Chinese comment in custom.css"""
    css_path = os.path.join(BASE, 'luxury-beauty-site', '.vitepress', 'theme', 'custom.css')
    with open(css_path, 'r', encoding='utf-8') as f:
        content = f.read()

    content = content.replace('/* 方案3：放大图片本身 */', '/* Option 3: Enlarge the image itself */')

    with open(css_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  Fixed CSS comment: {css_path}")


def update_internal_references():
    """Update internal references in config.mjs and other files to point to new paths"""
    config_path = os.path.join(BASE, 'luxury-beauty-site', '.vitepress', 'config.mjs')

    if os.path.exists(config_path):
        with open(config_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Update any Chinese path references
        replacements = {
            '01-技术选型说明/技术选型说明.md': '01-Technology-Selection/Technology-Selection.md',
            '02-项目架构/项目架构.md': '02-Project-Architecture/Project-Architecture.md',
            '04-设计规范/设计规范.md': '04-Design-Specification/Design-Specification.md',
            '05-SEO实现/SEO实现指南.md': '05-SEO-Implementation/SEO-Implementation-Guide.md',
            '06-关键功能实现/关键功能实现.md': '06-Key-Features/Key-Features-Implementation.md',
            '07-部署指南/部署指南.md': '07-Deployment-Guide/Deployment-Guide.md',
            '08-内容模型/内容模型.md': '08-Content-Model/Content-Model.md',
            '09-API接口/API接口.md': '09-API-Interface/API-Interface.md',
        }

        original = content
        for old, new in replacements.items():
            content = content.replace(old, new)

        if content != original:
            with open(config_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"  Updated references in: {config_path}")


def main():
    print("=" * 60)
    print("Step 1: Translate main/*.md files")
    print("=" * 60)

    md_files = [
        os.path.join(BASE, 'main', 'README.md'),
        os.path.join(BASE, 'main', '01-技术选型说明', '技术选型说明.md'),
        os.path.join(BASE, 'main', '02-项目架构', '项目架构.md'),
        os.path.join(BASE, 'main', '04-设计规范', '设计规范.md'),
        os.path.join(BASE, 'main', '05-SEO实现', 'SEO实现指南.md'),
        os.path.join(BASE, 'main', '06-关键功能实现', '关键功能实现.md'),
        os.path.join(BASE, 'main', '07-部署指南', '部署指南.md'),
        os.path.join(BASE, 'main', '08-内容模型', '内容模型.md'),
        os.path.join(BASE, 'main', '09-API接口', 'API接口.md'),
    ]

    for f in md_files:
        if os.path.exists(f):
            translate_file(f)
        else:
            print(f"  NOT FOUND: {f}")

    print()
    print("=" * 60)
    print("Step 2: Fix custom.css Chinese comment")
    print("=" * 60)
    fix_custom_css()

    print()
    print("=" * 60)
    print("Step 3: Translate Keyword Stats CSV")
    print("=" * 60)
    csv_file = os.path.join(BASE, 'Keyword Stats 2026-08-09 at 01_46_46.csv')
    if os.path.exists(csv_file):
        translate_csv_file(csv_file)

    print()
    print("=" * 60)
    print("Step 4: Rename directories and files to English")
    print("=" * 60)
    rename_directories()

    print()
    print("=" * 60)
    print("Step 5: Update internal references")
    print("=" * 60)
    update_internal_references()

    print()
    print("=" * 60)
    print("All translations complete!")
    print("=" * 60)


if __name__ == '__main__':
    main()
